# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: InstallMATLAB@0
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here    
      mkdir test 
      cat << EOF > 'test/tDemo.m'
      classdef tDemo < matlab.unittest.TestCase
        methods (Test)
         function test1(testCase)
            testCase.verifyEqual(testCase,5,5);
         end
         function test2(testCase)
            testCase.verifyEqual(testCase,5,6);
         end
        end
      end
      EOF
      cat << EOF > 'test/testHtml.m'
      import matlab.unittest.TestRunner;
      import matlab.unittest.TestSuite;
      import matlab.unittest.plugins.TestReportPlugin;
      suite = testsuite({'tDemo.m'});
      runner = TestRunner.withNoPlugins;
      htmlFolder = 'myHTMLFolder';
      plugin = TestReportPlugin.producingHTML(htmlFolder);
      runner.addPlugin(plugin);
      result = runner.run(suite);
      EOF
- task: RunMATLABCommand@0
  inputs:
    command: 'cd test;testHtml'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PublishHtmlReport@1
  inputs:
    reportDir: 'test/myHTMLFolder/index.html'
- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: '$(Agent.BuildDirectory)'
    Contents: 'test/myHTMLFolder'
    ArtifactName: 'HTMl report'
    ArtifactType: 'Container'